# Generated by Django 3.0.6 on 2020-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.TextField()),
            ],
        ),
    ]
