# Generated by Django 3.0.6 on 2020-05-22 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 22, 13, 48, 23, 120154, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
